#' Aggregate Returns by characteristic
#'
#' @param df_returns Return data frame, usually generated by `security_returns()`
#' @param df_info Info data frame, downloaded by `download_port_bbg()`
#' @param aggregate.by Column of info data frame to aggregate the returns by
#' @param col.id Name of the "id" column, should be the same for df_returns and df_info
#' @param col.weight Name of the weight column in df_info
#' @param col.date Name of the date column in df_returns
#' @param col.ret Name of the return column in df_returns
#'
#' @return Return aggregated return data frame
#' @export
#'
#' @importFrom dplyr left_join select join_by group_by summarize ungroup
#'
aggregate_returns <- function(df_returns,
                              df_info,
                              aggregate.by = mkt_sector,
                              col.id = id,
                              col.weight = weight,
                              col.date = date,
                              col.ret = ret){

  # select important columns from info data frame
  df_info <- df_info |> select(c({{col.id}}, {{aggregate.by}}, {{col.weight}}))

  # join returns with infos
  df <- df_returns |> left_join(df_info, by = join_by({{col.id}}))

  # aggregate returns
  df <- df |>
    group_by({{aggregate.by}}, {{col.date}}) |>
    summarize(
      date = first({{col.date}}),
      ret = sum({{col.ret}} * {{col.weight}}) / sum({{col.weight}})
    ) |>
    ungroup()


  return(df)
}
