#' Volatility Portfolio Decomposition
#'
#' This function computes the attribution of each asset in the portfolio
#' to the total portfolio volatility
#'
#'
#' @param df_returns Return data frame, usually generated by `security_returns()`
#' @param df_info Info data frame, downloaded by `download_port_bbg()`
#' @param col.id Name of the "id" column, should be the same for df_returns and df_info
#' @param col.weight Name of the weight column in df_info
#' @param col.date Name of the date column in df_returns
#' @param col.ret Name of the return column in df_returns
#'
#' @return
#' @export
#'
StdDev_decomposition <- function(df_returns,
                                 df_info,
                                 col.id = id,
                                 col.weight = weight,
                                 col.date = date,
                                 col.ret = ret){



  abc <- returns |>
    dplyr::arrange(id) |>
    pivot_wider(names_from = id, values_from = ret)

  abc <- xts(abc[, -1], order.by = as.Date(abc$date))

  help <- data.frame(id = names(abc))
  help <- left_join(help, info |> dplyr::select(id, Weight), by = "id")

  wgt <- help |> dplyr::select(Weight) |> dplyr::pull()


  test <- PerformanceAnalytics::StdDev(abc,
                                       clean = "boudt",
                                       portfolio_method = "component",
                                       weights = wgt)


}
