#' Volatility Portfolio Decomposition
#'
#' This function computes the attribution of each asset in the portfolio
#' to the total portfolio volatility
#'
#'
#' @param df_returns Return data frame, usually generated by `security_returns()`
#' @param df_info Info data frame, downloaded by `download_port_bbg()`
#' @param clean Cleaning Method for returns to choose. Default parameter is "boudt". Details can be found in the help section of `PerformanceAnalytics::StdDev`
#' @param col.id Name of the "id" column, should be the same for df_returns and df_info
#' @param col.weight Name of the weight column in df_info
#' @param col.date Name of the date column in df_returns
#' @param col.ret Name of the return column in df_returns
#'
#' @return Returns the a list of the risk decomposition by volatility for all assets in the portfolio.
#' @export
#'
#' @importFrom tidyr pivot_wider
#' @importFrom xts xts periodicity
#' @importFrom dplyr select left_join pull join_by
#' @importFrom PerformanceAnalytics StdDev
#'
StdDev_decomposition <- function(df_returns,
                                 df_info,
                                 clean = "boudt",
                                 col.id = id,
                                 col.weight = weight,
                                 col.date = date,
                                 col.ret = ret){


  # change returns to a xts format
  df_returns <- df_returns |>
    pivot_wider(names_from = {{col.id}}, values_from = {{col.ret}})

  df_returns <- df_returns |>
    select(-{{col.date}}) |>
    xts(order.by = df_returns |> select({{col.date}}) |> pull() |> as.Date())


  # write helper data frame to match asset returns to asset weights
  helper <- data.frame(id = names(df_returns))
  helper <- left_join(helper, df_info |> select({{col.id}}, {{col.weight}}), by = join_by({{col.id}}))

  # extract the weights
  wgt <- helper |> select({{col.weight}}) |> pull()
  wgt <- wgt / 100


  # compute the risk contribution
  result <- StdDev(df_returns,
                   clean = clean,
                   portfolio_method = "component",
                   weights = wgt)

  # figure out scale in order to annualize the StdDev
  scale <- switch(periodicity(df_returns)$scale,
                  "daily" = 252,
                  "weekly" = 52,
                  "monthly" = 12,
                  "quarterly" = 4,
                  "yearly" = 1)

  # annualize volatilities
  result$StdDev <- result$StdDev * sqrt(scale)
  result$contribution <- result$contribution * sqrt(scale)


  return(result)


}
